version: "3.8"

services:
  backend:
    image: ghcr.io/krishnambiyani/streamhub-backend:latest
    env_file:
      - ./backend/.env.production
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - streamhub-net

  rtmp-server:
    image: ghcr.io/krishnambiyani/streamhub-rtmp-server:latest
    container_name: rtmp-server
    ports:
      - "1935:1935"
      - "8080:80"
    volumes:
      - ./hls-data:/opt/data/hls:Z
    restart: unless-stopped
    networks:
      - streamhub-net

networks:
  streamhub-net:
    driver: bridge
